name: Docker Build and Push Container

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # TODO: Enable this step if not using network volume
            # - name: Free disk space
            #   run: |
            #       df -h
            #       sudo rm -rf /usr/share/dotnet
            #       sudo rm -rf /usr/local/lib/android
            #       sudo rm -rf /opt/ghc
            #       sudo rm -rf /opt/hostedtoolcache
            #       df -h

            - uses: actions/checkout@v3
              with:
                  ref: main

            - name: Generate version number
              id: version
              run: |
                  echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

            - name: Get Git commit hashes
              id: git_hashes
              run: |
                  echo "Getting latest commit hashes..."
                  COMFYUI_COMMIT=$(git ls-remote https://github.com/comfyanonymous/ComfyUI.git HEAD | cut -f1)
                  INSPIRE_PACK_COMMIT=$(git ls-remote https://github.com/ltdrdata/ComfyUI-Inspire-Pack.git HEAD | cut -f1)

                  echo "ComfyUI commit: $COMFYUI_COMMIT"
                  echo "Inspire Pack commit: $INSPIRE_PACK_COMMIT"

                  echo "COMFYUI_COMMIT_HASH=$COMFYUI_COMMIT" >> $GITHUB_OUTPUT
                  echo "INSPIRE_PACK_COMMIT_HASH=$INSPIRE_PACK_COMMIT" >> $GITHUB_OUTPUT

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                  driver: docker-container
                  buildkitd-flags: --debug

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build container and push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:${{ steps.version.outputs.VERSION }}
                  build-args: |
                      COMFYUI_COMMIT_HASH=${{ steps.git_hashes.outputs.COMFYUI_COMMIT_HASH }}
                      INSPIRE_PACK_COMMIT_HASH=${{ steps.git_hashes.outputs.INSPIRE_PACK_COMMIT_HASH }}
                  cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:buildcache,mode=max
                  platforms: linux/amd64
